---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: docs/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: docs/knowledge
  label: Knowledge
  create: all
  match: "**/*"
upload_dir: ".vuepress/public"
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
